upstream backend {
    server backend:8000;
}

server {
    listen 80;

    # Игнорировать фавикон
    location = /favicon.ico { access_log off; log_not_found off; }

    # Статические файлы (Django Admin, DRF)
    location /static/ {
        alias /app/static/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # Медиа файлы (если используются)
    location /media/ {
        alias /app/media/;
    }

    # Все остальные запросы проксируются на бэкенд (Django)
    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
