# Generated by Django 5.1.15 on 2026-06-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('branch_crm_id', models.IntegerField(unique=True, verbose_name='ID филиала в CRM')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название модуля')),
                ('validity_period', models.IntegerField(default=7, verbose_name='Период действия (дни)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_group_id', models.CharField(max_length=100, unique=True, verbose_name='ID группы из CRM')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('custom_aerodromnaya', models.BooleanField(default=False, verbose_name='Кастомная Аэродромная')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.branch', verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название локации')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.branch', verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО менеджера')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Уникальный телефон')),
                ('is_senior', models.BooleanField(default=False, verbose_name='Старший менеджер')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='core.location', verbose_name='Локация')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lessons/files/', verbose_name='Файл для просмотра (PDF)')),
                ('archive', models.FileField(upload_to='lessons/archives/', verbose_name='Архив для скачивания')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.module', verbose_name='Модуль')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_crm_id', models.CharField(max_length=100, unique=True, verbose_name='ID ученика из CRM')),
                ('student_name', models.CharField(max_length=255, verbose_name='ФИО ученика')),
                ('study_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала обучения')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.branch', verbose_name='Филиал')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.group', verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст резюме')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='core.student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='ParentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_reviews', to='core.student', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подкатегории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category', verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_crm_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID преподавателя из CRM')),
                ('tutor_name', models.CharField(max_length=255, verbose_name='ФИО преподавателя')),
                ('is_senior', models.BooleanField(default=False, verbose_name='Старший тьютор')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Уникальный телефон')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL аватара')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutors', to='core.branch', verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='TutorModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_modules', to='core.module', verbose_name='Модуль')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_modules', to='core.tutorprofile', verbose_name='Тьютор')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.tutorprofile', verbose_name='Тьютор'),
        ),
    ]
