# Generated by Django 5.1.15 on 2026-07-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['name'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='parentreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв родителей', 'verbose_name_plural': 'Отзывы родителей'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at'], 'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='tutormodule',
            options={'verbose_name': 'Доступ тьютора к модулю', 'verbose_name_plural': 'Доступы тьюторов к модулям'},
        ),
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'ordering': ['tutor_name'], 'verbose_name': 'Тьютор', 'verbose_name_plural': 'Тьюторы'},
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterUniqueTogether(
            name='tutormodule',
            unique_together={('tutor', 'module')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['branch'], name='group_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['tutor'], name='group_tutor_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['student'], name='resume_student_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch'], name='student_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group'], name='student_group_idx'),
        ),
        migrations.AddIndex(
            model_name='tutormodule',
            index=models.Index(fields=['tutor', 'expires_at'], name='tutormodule_tutor_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['branch'], name='tutor_branch_idx'),
        ),
    ]
