# Generated by Django 5.1.15 on 2026-07-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_crm_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID локации в CRM'),
        ),
    ]
