# Generated by Django 5.1.15 on 2026-07-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_crm_id_and_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_added',
            field=models.BooleanField(default=False, verbose_name='Резюме написано'),
        ),
    ]
