# Generated by Django 5.1.15 on 2026-07-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_is_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='subject_crm_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID предмета в CRM'),
        ),
    ]
