# Generated by Django 5.1.15 on 2026-07-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_subject_crm_id_to_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='custom_aerodromnaya',
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.location', verbose_name='Локация'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['location'], name='group_location_idx'),
        ),
    ]
