# Generated by Django 5.1.15 on 2026-07-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_group_custom_aerodromnaya_group_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_number'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер урока'),
        ),
    ]
