# Generated by Django 5.1.15 on 2026-08-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lesson_options_lesson_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='archive',
            field=models.FileField(blank=True, upload_to='lessons/archives/', verbose_name='Архив для скачивания'),
        ),
    ]
