# Generated by Django 5.1.15 on 2026-08-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lesson_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('category', models.CharField(choices=[('management', 'Руководство'), ('managers', 'Менеджеры'), ('methodological', 'Метод. и образовательный отдел'), ('marketing', 'Отдел маркетинга'), ('technical', 'Технический отдел')], max_length=50, verbose_name='Категория')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('telegram_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Telegram')),
                ('photo', models.FileField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.branch', verbose_name='Филиал (Город)')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
    ]
