# Generated by Django 5.1.15 on 2026-08-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_normalize_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Если включено, модуль доступен всем тьюторам и менеджерам без выдачи доступа', verbose_name='Доступен всем'),
        ),
    ]
